version: '2.0'

services:
    wordpress:
        image: wordpress:latest
        ports:
            - 80:80
        volumes:
            - ./data/wordpress:/var/www/html
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: password
        depends_on:
            - mysql
        networks:
            - wordpress-network
    mysql:
        image: mysql:latest
        volumes:
            - ./data/wp-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_ROOT_PASSWORD: password
        networks:
            - wordpress-network
networks:
    wordpress-network:
        driver: bridge